id: IE63A3883
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:00:42.403538
last_modified: 2023-02-09 15:00:42.403677
source_metadata:
  title: 'MSV 1,01: Pravrajyāvastu'
  language: bo
bases:
  8BB5:
    base_file: 8BB5.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
